_commit: adada77
_src_path: gh:monarch-initiative/koza-ingest-template
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: MIT
project_description: Ortholog ingest from PantherDB - transforms gene orthology relationships
    into Biolink model format
project_name: pantherdb-orthologs-ingest
project_slug: pantherdb_orthologs_ingest
