_commit: fe21eee73f47a659640e02590a3d72ca82f2ca35
_src_path: cookiecutter-monarch-ingest
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: MIT
project_description: Ortholog ingest from PantherDB - transforms gene orthology relationships into Biolink model format
project_name: pantherdb-orthologs-ingest
project_slug: pantherdb_orthologs_ingest
